def _initialize_page_metrics(page_num_actual: int) -> dict:
    """Initializes a dictionary to store metrics for a single page."""
    return {
        "page": page_num_actual,
        "time_sec_total_page_processing": 0.0,
        "time_sec_temp_pdf_creation": 0.0,
        "gemini_api_status": None, "gemini_response_length": 0, "gemini_error_message": "",
        "gemini_input_tokens": 0, "gemini_output_tokens": 0, "gemini_cost_usd": 0.0,
        "time_sec_gemini_layout": 0.0,
        "openai_api_status": None, "openai_response_length": 0, "openai_error_message": "",
        "openai_input_tokens": 0, "openai_output_tokens": 0, "openai_cost_usd": 0.0,
        "time_sec_openai_layout": 0.0,
        "genai_response_consolidation_status": None, "genai_response_consolidation_response_length": 0,
        "json_consolidation_error_message": "",
        "consolidation_input_tokens": 0, "consolidation_output_tokens": 0, "consolidation_cost_usd": 0.0,
        "time_sec_consolidation": 0.0,
        "sanitize_input_tokens": 0, "sanitize_output_tokens": 0, "sanitize_cost_usd": 0.0,
        "sanitize_status": "not attempted",
        "time_sec_sanitize": 0.0,
        "time_sec_hyperlink_extraction": 0.0,
        "hyperlink_extraction_status": "not attempted",
        "hyperlinks_found_count": 0,
        "hyperlink_input_tokens": 0,
        "hyperlink_output_tokens": 0,
        "hyperlink_cost_usd": 0.0,
        "hyperlink_error_message": "",
        "verification_status": "failed - verification not performed",
        "verification_input_tokens": 0, "verification_output_tokens": 0, "verification_cost_usd": 0.0,
        "time_sec_verification": 0.0,
        "direct_text_extraction_status" : "not_attempted", "direct_text_char_count" : 0, "ocr_text_extraction_status" : "not_attempted", "ocr_text_char_count" : 0
    }