# -- Google cloud project details --
google_cloud:
    project_id: "studied-glow-468203-f5"
    region: "us"

# -- AI model configuration --
models:
    gemini:
        model: "models/gemini-2.5-pro-preview-05-06"
        base_url: "https://generativelanguage.googleapis.com/v1beta"
        pricing:
            input_per_million: 2.50
            output_per_million: 15.00

# -- Database connection details --
database:
    dialect: "mysql"
    driver: "mysqlconnector"
    host: "juris-data.crkmq80swpic.ap-southeast-2.rds.amazonaws.com"
    port: "3306"
    name: "legal_store"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"

# -- AWS connection details --
aws:
    default_region: "ap-southeast-2"
    s3:
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/nt/"
        jurisdiction_code: "NT"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/act/"
        jurisdiction_code: "ACT"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/qld/"
        jurisdiction_code: "QLD"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/sa/"
        jurisdiction_code: "SA"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/tas/"
        jurisdiction_code: "TAS"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/vic/"
        jurisdiction_code: "VIC"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/wa/"
        jurisdiction_code: "WA"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/nsw/"
        jurisdiction_code: "NSW"
      - bucket_name: "legal-store"
        s3_dest_folder: "case-laws/commonwealth/"
        jurisdiction_code: "FED"
    # Credentials are now loaded from the .env file
    access_key_id: "${AWS_ACCESS_KEY_ID}"
    secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    
# List of tables to be read by the connector
tables:
  tables_to_read:
    - database: legal_store
      table: caselaw_registry
      
  tables_to_write:
    - database: legal_store
      table: caselaw_enrichment_status
      columns:
        processing_status: "status_metadataextract"
        processing_duration: "duration_metadataextract"
        start_time: "start_time_metadataextract"
        end_time: "end_time_metadataextract"
        token_input: "token_input_metadataextract"
        token_output: "token_output_metadataextract"
        token_input_price: "token_input_price_metadataextract"
        token_output_price: "token_output_price_metadataextract"

    - database: legal_store
      table: caselaw_metadata
      columns:
        citation: "citation"
        key_issues: "key_issues"
        keywords: "keywords"
        presiding_officer: "presiding_officer"
        panelist: "panelist"
        orders: "orders"
        decision: "decision"
        judgment_date: "judgment_date"
        cases_cited: "cases_cited"
        legislation_cited: "legislation_cited"
        file_no: "file_no"
        hearing_dates: "hearing_dates"
        matter_type: "matter_type"
        parties: "parties"
        category: "category"
        bjs_number: "bjs_number"
        court_type: "court_type"
        counsel: "counsel"
        law_firm_agency: "law_firm_agency"
        hearing_location: "hearing_location"
        incident_date: "incident_date"
        affected_sectors: "affected_sectors"
        practice_areas: "practice_areas"
        representation: "representation"

    - database: legal_store
      table: mapping_counsel_firm
      columns:
        counsel: "counsel"
        law_firm_agency: "law_firm_agency"

# -- File to process --
enrichment_filenames:
  source_file: "summary.html"
  jurismetadata_json: "jurismetadata.json"

# -- Registry details
tables_registry:
    database: "legal_store"
    table: "caselaw_registry"
    column: "year"
    processing_years: [2025,2024]

# -- Extraction switch
extraction_switch:
    rulebased_extract: True
    AI_extract: True